#ifndef COFFEEWARMERCORE_GLOBAL_H
#define COFFEEWARMERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COFFEEWARMERCORE_LIBRARY)
#  define COFFEEWARMERCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define COFFEEWARMERCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COFFEEWARMERCORE_GLOBAL_H
